### ISSUE TITLE
Fails on Samsung ARM Chromebook

### ISSUE THREAD

**Issue by DevanWolf** [ethanmad/chromeos-resize#2]
When I try to get more free space on my Samsung ARM based Chromebook by running cros-resize, I get this error and I don't know how to get this through. It worked fine on other Chromebooks.
ERROR: Entry outside of valid region
ERROR: -i 7 -l ROOT-C -b 19288064 -s 11489247

**Comment by ethanmad** [comment]
Sorry for the delay in responding. Good to hear it worked on your other devices, but I hope we can fix it for this one.

If you still need help, can you tell me the output of `lsblk` and the inputs/options you are using?
