### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Xichen96** [ethanmad/chromeos-resize#3]
I tried on chromium, and it shows Ending LBA overlaps and -i 1 -l STATE -b 64 -s 61440000 as error message. Any chance you know what was happening?

**Comment by ethanmad** [comment]
I don't know. Can you tell me which device you are using, output of `lsblk`, and your inputs?

**Comment by Xichen96** [comment]
At first it was the checking for developer mode thing, since I use a chromium os, i just manually  set the value. Then I it's just what i wrote up there. I figured out a way to deal with it, using a live ubuntu's gparted to partition. Just delete KERN-C ROOT-C and create 2 new ones of the sizes of my choosing.

**Comment by maxdruiz** [comment]
I am experiencing a similar issue on a Pixelbook Go, default inputs, with the error:

Unmounting stateful partition...
Editing partition table...
ERROR: Starting LBA overlaps
ERROR: -i 1 -l STATE -b 17092608 -s 10485760 


Output of lsblk:

NAME          MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0           7:0    0 315.8M  0 loop 
`-encstateful 253:1    0 315.8M  0 dm   /mnt/stateful_partition/encrypted
loop1           7:1    0 486.1M  1 loop /opt/google/containers/android/rootfs/root
loop2           7:2    0     4K  1 loop /opt/google/containers/arc-sdcard/mountpoints/container-root
loop3           7:3    0     4K  1 loop /opt/google/containers/arc-obb-mounter/mountpoints/container-root
loop4           7:4    0   9.2M  1 loop /usr/share/chromeos-assets/quickoffice/_platform_specific
loop5           7:5    0  58.6M  1 loop 
sda             8:0    1  28.7G  0 disk 
`-sda1          8:1    1  28.7G  0 part /media/removable/USB Drive
mmcblk0       179:0    0  58.2G  0 disk 
|-mmcblk0p1   179:1    0   1.1G  0 part /mnt/stateful_partition
|-mmcblk0p2   179:2    0    16M  0 part 
|-mmcblk0p3   179:3    0     4G  0 part 
|-mmcblk0p4   179:4    0    16M  0 part 
|-mmcblk0p5   179:5    0     4G  0 part 
|-mmcblk0p6   179:6         16M  0 part 
|-mmcblk0p8   179:8         16M  0 part /usr/share/oem
|-mmcblk0p9   179:9        512B  0 part 
|-mmcblk0p10  179:10       512B  0 part 
|-mmcblk0p11  179:11         8M  0 part 
`-mmcblk0p12  179:12        32M  0 part 
mmcblk0boot0  179:16   0     4M  1 disk 
mmcblk0boot1  179:32   0     4M  1 disk 
mmcblk0rpmb   179:48   0    16M  0 disk 
zram0         252:0    0  11.3G  0 disk [SWAP]
