### ISSUE TITLE
How can I run this on CloudReady when running of a USB?

### ISSUE THREAD

**Issue by nekename** [ethanmad/chromeos-resize#7]
Not really an issue... but
I installed CloudReady Home edition, and I am running this of an USB Drive because I still want to use the default Chrome OS. 

I can't switch to Developer mode, because when it shows me the recovery screen after pressing Esc+Refresh+Power, it says the disk I inserted does not contain Chrome OS, with no way to let me press Control+D. (it says that because it detects my CloudReady drive).

However, I want to resize my partitions with this amazing tool that worked on non-CloudReady, but it is not letting me because I can't get in to Developer mode.

**Comment by ethanmad** [comment]
I don't know what CloudReady is and don't think I have the expertise to help.  Maybe the CloudReady support channels would be more useful.

If you find an answer, could you follow up to this issue with instructions in case there is future interest?

If any issues come up that are about this tool, I can try to help.

**Comment by ethanmad** [comment]
I looked up CloudReady just now and see that it's an installation method for Chromium OS.

Based on your original comment, my understanding is that you want to resize the partitions on your USB drive so that CloudReady will share the USB drive space with another operating system. Is that correct? If so, I think you can make it work by replacing [`DISK=$(rootdev -d -s)`](https://github.com/ethanmad/chromeos-resize/blob/e5e4931c9a219937288dffaf8f2b925fdc84fcb9/cros-resize.sh#L35) with `DISK=/dev/sdb` or whatever the disk's name is.

You should be able to boot into Chrome OS, download and modify the script, then run it, assuming CloudReady uses the same partition layout as does Chrome OS. If not, you can try another tool, like parted.

**Comment by nekename** [comment]
Sorry. I didn't specify what CloudReady was.
CloudReady is a Chromium OS branch developed by Neverware ([neverware.com](https://neverware.com)).

You can run the Home edition (free) off a USB Drive, which is practically Chrome OS on a USB. I want to change the size of my USB Drive's STATE partition, but as mentioned in my previous comment, I can't enable Developer Mode.

**Comment by ninjadev64** [comment]
I have not installed CloudReady on the computer, I have installed it to run off a USB drive. I want to resize the STATE partition on the USB, but Developer Mode cannot be enabled when using a USB to run CloudReady.

**Comment by nekename** [comment]
> I looked up CloudReady just now and see that it's an installation method for Chromium OS.
> 
> Based on your original comment, my understanding is that you want to resize the partitions on your USB drive so that CloudReady will share the USB drive space with another operating system. Is that correct? If so, I think you can make it work by replacing [`DISK=$(rootdev -d -s)`](https://github.com/ethanmad/chromeos-resize/blob/e5e4931c9a219937288dffaf8f2b925fdc84fcb9/cros-resize.sh#L35) with `DISK=/dev/sdb` or whatever the disk's name is.
> 
> You should be able to boot into Chrome OS, download and modify the script, then run it, assuming CloudReady uses the same partition layout as does Chrome OS. If not, you can try another tool, like parted.

I'll try that, it may still work.

**Comment by nekename** [comment]
I tried it and got the error: `ERROR: Can't open /dev/sdb: No such file or directory`
Is this the wrong name?
Just so you know, I removed the check for developer mode section. Is that fine?
I read somewhere that most developer mode features work on normal CloudReady anyway... so it should be fine.

**Comment by nekename** [comment]
Alright.. now I used the default script except without the developer mode message.
But then I got this error:
```
ERROR: Entry outside of valid region
ERROR: -i 1 -l STATE -b 64 -s 33554432 
```
Or sometimes with different sizes:
```
ERROR: Ending LBA overlaps
ERROR: -i 1 -l STATE -b 64 -s 4096000 
```
But I am always getting the error:
`ERROR: -i 1 -l STATE -b 64 -s 4096000`

**Comment by ethanmad** [comment]
Try using parted or another disk resizing tool to do it manually. Something
seems to be wrong with the script and I'm not really sure what.
