### ISSUE TITLE
Entry outside of valid region

### ISSUE THREAD

**Issue by palewire** [ethanmad/chromeos-resize#8]
I got this error trying to follow the instructions in crosh
![PXL_20221231_011058791](https://user-images.githubusercontent.com/9993/210120714-13531094-a895-4e76-b073-1672bfb494ab.jpg)

**Comment by ethanmad** [comment]
I think you can probably debug this yourself. The arithmetic used in calculations is not very complicated, but I don't have the information to help you in this image. If you don't want to, you can try using chrx or parted.

**Comment by palewire** [comment]
Thanks. The issue was that the math was slightly off. I fixed it by calculating the numbers manually, as you suggested.

**Comment by ethanmad** [comment]
Glad to hear you fixed it! You can submit a PR if it seems like something
happening consistently.
